name: Build zed-csi artifacts
on: push

jobs:
  build:
    name: Build zed-csi
    runs-on: 'ubuntu-20.04'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binary artifacts
        run: ./build/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: zed-csi
          path: ./out/zed-csi.*.lz

      - name: Create release with assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./out/zed-csi.*.lz

      - name: Create release with assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: startsWith(github.ref, 'refs/tags/')

      - name: Login to container registry
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Crossbuild
        if: startsWith(github.ref, 'refs/tags/')
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f dist.dockerfile \
            --build-arg CSIVERSION=${GITHUB_REF#refs/tags/} \
            -t "ghcr.io/zed-csi/zed-csi:${GITHUB_REF#refs/tags/}" \
            -t "ghcr.io/zed-csi/zed-csi:build-$(date '+%Y%m%d%H%M')" --push .
