name: Build Containers

on:
  push:
    branches:
      - main

jobs:
  zoneminder:
    name: Build zed-csi containers

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        run: |-
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Crossbuild
        run: |-
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "ghcr.io/zed-csi/zed-csi:dev" \
            -t "ghcr.io/zed-csi/zed-csi:dev-$(date '+%Y%m%d%H%M')" --push .
