name: Build
on: push

jobs:
  build:
    name: Build zed-csi

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build binary artifacts
        run: |-
          ./build/build.sh
